# Generated by Django 5.0.6 on 2024-06-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_basetimerefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetimerefund',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
