# Generated by Django 5.0.6 on 2024-06-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_basetimerefund_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepercent',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
