# Generated by Django 5.0.6 on 2024-06-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_basepercent_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='license_plate',
        ),
    ]
