# Generated by Django 5.0.6 on 2024-06-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_car_license_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseprice',
            old_name='date_time',
            new_name='created',
        ),
    ]
