# Generated by Django 5.0.6 on 2024-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_travel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
