# Generated by Django 5.0.6 on 2024-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_ticket_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='seat_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
