# Generated by Django 5.0.6 on 2024-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transectionlog_transection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_percent', models.IntegerField()),
            ],
        ),
    ]
