# Generated by Django 5.0.6 on 2024-06-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_basetimerefund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseTimeRefund',
        ),
    ]
